#
# Copyright (C) 2015 Imagination Technologies
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y						= mfio.o
obj-y						+= pistachio.o
obj-$(CONFIG_SPL_BUILD)		+= clocks.o
obj-$(CONFIG_SPL_BUILD)		+= lowlevel_init.o
obj-$(CONFIG_SPL_BUILD)		+= spl_boot.o
